---

- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: Installing Apache2 Package
    apt:
      name: apache2
      state: absent

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
